version: '3.8'
services:
  order-service:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/orders
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
