openapi: 3.0.0
info:
  title: Order Service API
  version: 1.0.0
  description: REST API for managing orders in an e-commerce platform.
servers:
  - url: http://localhost:3000

paths:
  /:
    get:
      summary: Health check
      responses:
        '200':
          description: Order Service is running

  /orders:
    post:
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: string
                      quantity:
                        type: integer
                totalAmount:
                  type: number
      responses:
        '201':
          description: Order created successfully
        '400':
          description: Failed to create order or reduce stock

    get:
      summary: Get all orders
      responses:
        '200':
          description: A list of orders

  /orders/{id}:
    get:
      summary: Get order by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Order found
        '404':
          description: Order not found

    delete:
      summary: Delete an order
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Order deleted
        '404':
          description: Order not found

components:
  schemas:
    Order:
      type: object
      properties:
        userId:
          type: string
        items:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
              quantity:
                type: integer
        totalAmount:
          type: number
        status:
          type: string
        createdAt:
          type: string
          format: date-time